apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
  selector:
    app: guestbook-ui
